version: '3'
services:

  gtranslate:
    build: .
    restart: unless-stopped
    # ports:
    #  - 5000:${LISTEN_PORT:-5000}
    # environment:
    #  - PROXY=http://localhost:5000
    #  - LISTEN_PORT=5000
    #  - STATIC_DIR=./static
    #  - TEMPLATES_DIR=./templates
    #  - USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

# Tor support can be added by changing PROXY
# to something like socks5://localhost:9050
# Instructions to add tor from docker here: https://community.torproject.org/relay/setup/bridge/docker/
